name: Upload release assets

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  
jobs:
  upload-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Replace hardcoded URL in Nordpool.js
        run: |
          export LANG=C.UTF-8
          export LC_ALL=C.UTF-8
          sed -i 's#https://raw.githubusercontent.com/flopp999/Scriptable-NordPool/main/#https://github.com/flopp999/Scriptable-NordPool/releases/latest/download/#g' Nordpool.js
          sed -i 's#FileManager\.iCloud()#FileManager.local()#g' Nordpool.js
      
      - name: Upload assets to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Nordpool.js
            Translations.json
            Version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
